name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Define all environment variables for the job here
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc" # Read Node.js version from .nvmrc

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        if: ${{ success() }}

      - name: Build
        run: npm run build
        if: ${{ success() }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ success() }}
        with:
          # Set environment later if we have UAT or PROD later.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: ${{ secrets.CNAME }}
